### ISSUE TITLE
Incentive amount allocated before changing donation amount invalidates settings

### ISSUE THREAD

**Issue by juyoung101** [GamesDoneQuick/donation-tracker#170]
At /tracker/ui/donate, if a donation amount is set and then an incentive is selected, the incentive allocation could end up being greater than the donation amount if the donation amount gets changes. This results in the following error on the page:

> Unable to update the settings, those are invalid: [Error: The value [25] being set falls outside of the minimumValue [0.00] and maximumValue [2.00] range set for this element]

Steps to reproduce:

1. Navigate to /tracker/ui/donate (e.g. https://gamesdonequick.com/tracker/ui/donate/28)
2. Enter a donation amount (e.g. $25.00)
3. Under Incentives, select Add Incentives
4. Select an incentive (e.g. a bonus game incentive, which will pre-allocate the donation amount to the incentive)
5. Return to the donation amount and alter the amount so that the donation amount is less than the incentive amount. (e.g. backspace the 5 in 25 to change the value to 26. The value will temporarily be 2.)
6. Notice that the donation form is replaced with an error message and a stacktrace (included below.

Stacktrace: 
`Error: Unable to update the settings, those are invalid: [Error: The value [50] being set falls outside of the minimumValue [0.00] and maximumValue [25.00] range set for this element]
    at Function.value (https://gamesdonequick.com/static/tracker/gen/tracker-tracker-cc34d87aaade3b948e1b.js:39:102542)
    at e.value (https://gamesdonequick.com/static/tracker/gen/tracker-tracker-cc34d87aaade3b948e1b.js:39:195909)
    at t.value (https://gamesdonequick.com/static/tracker/gen/tracker-tracker-cc34d87aaade3b948e1b.js:39:75611)
    at Ao (https://gamesdonequick.com/static/tracker/gen/tracker-tracker-cc34d87aaade3b948e1b.js:23:51474)
    at Xa (https://gamesdonequick.com/static/tracker/gen/tracker-tracker-cc34d87aaade3b948e1b.js:23:69469)
    at Cs (https://gamesdonequick.com/static/tracker/gen/tracker-tracker-cc34d87aaade3b948e1b.js:23:105897)
    at Al (https://gamesdonequick.com/static/tracker/gen/tracker-tracker-cc34d87aaade3b948e1b.js:23:90221)
    at Nl (https://gamesdonequick.com/static/tracker/gen/tracker-tracker-cc34d87aaade3b948e1b.js:23:90146)
    at Sl (https://gamesdonequick.com/static/tracker/gen/tracker-tracker-cc34d87aaade3b948e1b.js:23:87486)
    at https://gamesdonequick.com/static/tracker/gen/tracker-tracker-cc34d87aaade3b948e1b.js:23:45816`

**Comment by faultyserver** [comment]
Nice catch! This is an interesting bug that I think stems from the underlying library powering the currency input being overly-strict about its value.

I plan on looking at this fairly soon, though obviously now that AGDQ is over it won’t be making it in before then.

Thanks for opening this issue! I hadn’t encountered this case until now.

**Comment by faultyserver** [comment]
Hello from the future. I finally went back and looked at what was causing this and was able to fix it in 719c350c973d935357d106d7060104415e763164 (accidentally pushed to master instead of making a PR).

Now, when changing the total donation amount, the incentive allocation will automatically decrease to match the remaining available amount. 

https://user-images.githubusercontent.com/783733/233809010-dd24938a-276f-4813-836a-402fae0f87a8.mov
